import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty } from 'class-validator';

export class VerifyWalletDto {
  @ApiProperty({
    description: 'The message that was signed by the wallet',
    example: 'Sign this message to verify your wallet ownership',
  })
  @IsString()
  @IsNotEmpty()
  message: string;

  @ApiProperty({
    description: 'The signature generated by signing the message with the wallet',
    example: '0x123...',
  })
  @IsString()
  @IsNotEmpty()
  signature: string;
}